name: "Deploy"

permissions:
  contents: read

on:
  push:
    branches:
      - main
  schedule:
    - cron: "37 1 1/7 * *"

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets:
      GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: deployment
    needs: build

    steps:
    - name: Download build production
      uses: actions/download-artifact@v4
      with:
        name: build-production

    - name: "Setup SSH Key"
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 0600 ~/.ssh/id_ed25519
        ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: "Sync"
      run: rsync -avz --delete-before build_production/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ vars.DEPLOY_PATH }}
