name: "Deploy"

permissions:
  contents: read

on:
  push:
    branches:
      - main
  schedule:
    - cron: "37 1 1/7 * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: deployment

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - uses: ./github/workflows/build.yaml

    - name: "Setup SSH Key"
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 0600 ~/.ssh/id_ed25519
        ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: "Sync"
      run: rsync -avz --delete-before build_production/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ vars.DEPLOY_PATH }}
